name: fanfou_backup

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 10 * * *
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.9

      - name: Setup Python requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install - requirements.txt
          
      - name: Backup JSON & images
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          echo "$TEST_TOKEN"
          # python ./backup_json.py 1 2 3 4 5
